services:
  postgres:
    image: postgres:15-bullseye
    environment:
      POSTGRES_DB: root
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - 15432:5432
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d root']
      interval: 10s
      timeout: 5s
      retries: 5